change theme color

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -34,32 +34,32 @@ jobs:
 
       - name: Change Colors in Dart Code (AppTheme)
         run: |
-          # Ensure the file path is correct
-          FILE_PATH="lib/infrastructure/theme/theme.dart"
-
-          # Check if the file exists
-          if [ -f "$FILE_PATH" ]; then
-            echo "File found: $FILE_PATH"
-            echo "File contents before modification:"
-            cat "$FILE_PATH"
-
-            # Use `perl` to replace color values in the Dart file
-             sed -i '' 's/primary: Colors\.[a-zA-Z]\+/primary: const Color(0xFF123456)/g' "$FILE_PATH"
-#            perl -pi -e 's/0xFF00A3E0/0xff007bff/g' "$FILE_PATH"
-#            perl -pi -e 's/0xFF13a1db/0xffdc3545/g' "$FILE_PATH"
-
-            echo "File contents after modification:"
-            cat "$FILE_PATH"
-
-            # Configure git and commit changes
-            git config --global user.name "github-actions[bot]"
-            git config --global user.email "github-actions[bot]@users.noreply.github.com"
-            git add "$FILE_PATH"
-            git commit -m "Automated: Change colors in Dart code" || echo "No changes to commit"
-          else
-            echo "File not found: $FILE_PATH"
-            exit 1
-          fi
+               # Ensure the file path is correct
+               FILE_PATH="lib/infrastructure/theme/theme.dart"
+               
+               # Check if the file exists
+               if [ -f "$FILE_PATH" ]; then
+               echo "File found: $FILE_PATH"
+               echo "File contents before modification:"
+               cat "$FILE_PATH"
+               
+               # Use `perl` to replace color values in the Dart file
+               sed -i '' 's/primary: Colors\.[a-zA-Z]\+/primary: const Color(0xFF123456)/g' "$FILE_PATH"
+          #            perl -pi -e 's/0xFF00A3E0/0xff007bff/g' "$FILE_PATH"
+          #            perl -pi -e 's/0xFF13a1db/0xffdc3545/g' "$FILE_PATH"
+               
+               echo "File contents after modification:"
+               cat "$FILE_PATH"
+          
+          # Configure git and commit changes
+               git config --global user.name "github-actions[bot]"
+               git config --global user.email "github-actions[bot]@users.noreply.github.com"
+               git add "$FILE_PATH"
+               git commit -m "Automated: Change colors in Dart code" || echo "No changes to commit"
+               else
+               echo "File not found: $FILE_PATH"
+               exit 1
+               fi
         shell: /usr/bin/bash -e {0}
         env:
           FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.29.0-x64
